### PR TITLE
-Loadash Issue Resolve in AdminLTETheme

### PR DESCRIPTION
**Pull request by 1MuneebUrRehman**

### CODE REVIEW

**Comment by 1MuneebUrRehman** [comment]
I have installed other themes such as "core ui" and "sb admin2", and I have not faced any problems like Lodash. However, I did notice that in the adminlte theme, the bootstrap.js file requires the import of Lodash. I hope this information proves helpful!

image

**Comment by krekas** [comment]
So can you remove completely loadash from this theme and try if it works?

**Comment by 1MuneebUrRehman** [comment]
I have seen that all bootstrap themes require loadash except this three coreui, voltbs5, and sb-admin-2. You can check by going to  "resources/stubs/ui/theme/js/bootstrap.js".

**Comment by krekas** [comment]
Can you fix it or not?

**Comment by 1MuneebUrRehman** [comment]
Like this PR, if you think is right. I can add that code to those themes as well.

**Comment by krekas** [comment]
Have you tried completely removing it?

**Comment by 1MuneebUrRehman** [comment]
No, I just removed it (import loadash) from bootstrap.js locally. it seems to work but not sure about that.

**Comment by PovilasKorop** [comment]
Closing in favor of #126

**Pull request closed without merging**
