### PR TITLE
fix: change laravel/ui version to version without errors.

### PR DESCRIPTION
**Pull request by gbretas**
@krekas see now please.

Only changed version and works..

### CODE REVIEW

**Comment by krekas** [comment]
@gbretas hard coding version isn't good. When Laravel 11 comes out next month or any other version with fixes who will come here and fix it?

**Comment by gbretas** [comment]
I’ll do.

The error is in laravel/ui.

This is the solution.

Em seg., 19 de fev. de 2024 às 03:51, Nerijus ***@***.***>
escreveu:

**Comment by PovilasKorop** [comment]
@krekas I actually approve in this case, because, as I understand, this fixes from non-working solution to working solution, so it's already an improvement, if there's no other way currently.

Later when we need to change the version again, someone will do it when they discover new bugs. It's not a big change, so makes sense to me.

Agree to merge?

Thanks @gbretas

**Comment by gbretas** [comment]
Yes, I personally agree.

Em seg., 19 de fev. de 2024 às 09:08, PovilasKorop ***@***.***>
escreveu:

**Pull request merged**
