### PR TITLE
add laravel-ui tabler.io

### PR DESCRIPTION
**Pull request by PierreLebedel**

### CODE REVIEW

**Review by PierreLebedel — COMMENTED** [review]
Fix login remember checkbox name for cookie

**Comment by PovilasKorop** [comment]
@PierreLebedel thanks for the contribution! I will schedule to review it next week, now busy with Laravel 9 related work.

**Comment by PierreLebedel** [comment]
@PovilasKorop There is no rush, I suspect that the release of Laravel 9 involves a lot of work (and a lot of daily content for us ;) !

**Comment by krekas** [comment]
@PierreLebedel please make some fixes

1. Remove search input
image

2. Remove bell icon
image

3. On users page add info message like on other templates `Sample table page`

4. On about page remove buttons 
image

When done ping Povilas :wink:

**Comment by PierreLebedel** [comment]
It's done! My bad, I thought putting some unnecessary components was a good idea. I removed the indicated elements and a few others to simplify the templates files. Thank you. Ping @PovilasKorop

**Comment by PovilasKorop** [comment]
@PierreLebedel thanks a lot for your work, I've just released the `v1.4` with Tabler :)

**Pull request merged**
