### PR TITLE
update laravel ui and bootstrap version

### PR DESCRIPTION
**Pull request by RoduanKD**
Hello!
I'm working on this now and here's the required todo

- [x] update bootstrap and laravel/ui in the install command
- [x] update vite.config.js with new `~bootstrap` alias
- [x] update app.blade.php and guest.blade.php in all themes with `vite` directive
   - [x] Admin LET (no change required)
   - [x] Core UI
   - [x] Plain Admin
   - [x] SB admin 2
   - [x] tabler
   - [x] voltbs5
- [x] replace `require` with `import` since Vite doesn't support it

### CODE REVIEW

**Comment by krekas** [comment]
@RoduanKD keep in mind that there's very big chance not all themes will work only by changing to `@vite` directive.

**Comment by RoduanKD** [comment]
I've tested manually all `laravel/ui` themes. all of them are fine except for Volt. please give it a second check @PovilasKorop @krekas. I'm not sure if the problem is from my side or no.

error details:
```
D:\laragon\www\larastarters\node_modules\sass\sass.dart.js:27142
      throw error;
      ^

Invalid argument(s): Uri d:%5Claragon%5Cwww%5Clarastarters%5Cnode_modules%5C@fortawesome%5Cfontawesome-free%5Cscss%5Csolid.scss must have scheme 'file:'.
    at Object.wrapException (D:\laragon\www\larastarters\node_modules\sass\sass.dart.js:1235:17)
    at WindowsStyle.pathFromUri$1 (D:\laragon\www\larastarters\node_modules\sass\sass.dart.js:32890:17)
    at StaticClosure.fromUri (D:\laragon\www\larastarters\node_modules\sass\sass.dart.js:16100:37)
    at Object.NullableExtension_andThen0 (D:\laragon\www\larastarters\node_modules\sass\sass.dart.js:18332:40)
    at Object._wrapException (D:\laragon\www\larastarters\node_modules\sass\sass.dart.js:12997:14)
    at _render_closure1.call$2 (D:\laragon\www\larastarters\node_modules\sass\sass.dart.js:81147:21)
    at _RootZone.runBinary$3$3 (D:\laragon\www\larastarters\node_modules\sass\sass.dart.js:27268:18)
    at _FutureListener.handleError$1 (D:\laragon\www\larastarters\node_modules\sass\sass.dart.js:25818:19)
    at _Future__propagateToListeners_handleError.call$0 (D:\laragon\www\larastarters\node_modules\sass\sass.dart.js:26116:49)
    at Object._Future__propagateToListeners (D:\laragon\www\larastarters\node_modules\sass\sass.dart.js:4539:77) {
  dartException: <ref *1> ArgumentError {
    _hasValue: false,
    invalidValue: null,
    name: null,
    message: "Uri d:%5Claragon%5Cwww%5Clarastarters%5Cnode_modules%5C@fortawesome%5Cfontawesome-free%5Cscss%5Csolid.scss must have scheme 'file:'.",
    '$thrownJsError': <ref *2> Invalid argument(s): Uri d:%5Claragon%5Cwww%5Clarastarters%5Cnode_modules%5C@fortawesome%5Cfontawesome-free%5Cscss%5Csolid.scss must have scheme 'file:'.
        at Object.wrapException (D:\laragon\www\larastarters\node_modules\sass\sass.dart.js:1235:17)
        at WindowsStyle.pathFromUri$1 (D:\laragon\www\larastarters\node_modules\sass\sass.dart.js:32890:17)
        at StaticClosure.fromUri (D:\laragon\www\larastarters\node_modules\sass\sass.dart.js:16100:37)
        at Object.NullableExtension_andThen0 (D:\laragon\www\larastarters\node_modules\sass\sass.dart.js:18332:40)
        at Object._wrapException (D:\laragon\www\larastarters\node_modules\sass\sass.dart.js:12997:14)
        at _render_closure1.call$2 (D:\laragon\www\larastarters\node_modules\sass\sass.dart.js:81147:21)
        at _RootZone.runBinary$3$3 (D:\laragon\www\larastarters\node_modules\sass\sass.dart.js:27268:18)
        at _FutureListener.handleError$1 (D:\laragon\www\larastarters\node_modules\sass\sass.dart.js:25818:19)
        at _Future__propagateToListeners_handleError.call$0 (D:\laragon\www\larastarters\node_modules\sass\sass.dart.js:26116:49)
        at Object._Future__propagateToListeners (D:\laragon\www\larastarters\node_modules\sass\sass.dart.js:4539:77) {
      dartException: [Circular *1],
      '$cachedTrace': _StackTrace {
        _exception: [Circular *2],
        _trace: "Invalid argument(s): Uri d:%5Claragon%5Cwww%5Clarastarters%5Cnode_modules%5C@fortawesome%5Cfontawesome-free%5Cscss%5Csolid.scss must have scheme 'file:'.\n" +
          '    at Object.wrapException (D:\\laragon\\www\\larastarters\\node_modules\\sass\\sass.dart.js:1235:17)\n' +
          '    at WindowsStyle.pathFromUri$1 (D:\\laragon\\www\\larastarters\\node_modules\\sass\\sass.dart.js:32890:17)\n' +
          '    at StaticClosure.fromUri (D:\\laragon\\www\\larastarters\\node_modules\\sass\\sass.dart.js:16100:37)\n' +
          '    at Object.NullableExtension_andThen0 (D:\\laragon\\www\\larastarters\\node_modules\\sass\\sass.dart.js:18332:40)\n' +
          '    at Object._wrapException (D:\\laragon\\www\\larastarters\\node_modules\\sass\\sass.dart.js:12997:14)\n' +
          '    at _render_closure1.call$2 (D:\\laragon\\www\\larastarters\\node_modules\\sass\\sass.dart.js:81147:21)\n' +
          '    at _RootZone.runBinary$3$3 (D:\\laragon\\www\\larastarters\\node_modules\\sass\\sass.dart.js:27268:18)\n' +
          '    at _FutureListener.handleError$1 (D:\\laragon\\www\\larastarters\\node_modules\\sass\\sass.dart.js:25818:19)\n' +
          '    at _Future__propagateToListeners_handleError.call$0 (D:\\laragon\\www\\larastarters\\node_modules\\sass\\sass.dart.js:26116:49)\n' +
          '    at Object._Future__propagateToListeners (D:\\laragon\\www\\larastarters\\node_modules\\sass\\sass.dart.js:4539:77)'
      }
    }
  }
}
```

**Comment by krekas** [comment]
@RoduanKD your error is with fontawesome. It cannot find manifest file

**Comment by RoduanKD** [comment]
this issue was related to sass according to [this](https://github.com/vitejs/vite/issues/4026#issuecomment-900563464) I need to update `sass` to `1.38`. it fixes the problem but puts me back one step because as of `sass:1.32`, using / operator is not allowed and shows a deprecation notice. I fixed the deprecations that are coming from volt (using sass-migrator) and the ones that are left are the ones coming from font awesome

```
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(20em, 16) or calc(20em / 16)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
12 │ $fa-fw-width:          (20em / 16);
   │                         ^^^^^^^^^
   ╵
    node_modules\@fortawesome\fontawesome-free\scss\_variables.scss 12:25  @import
    node_modules\@fortawesome\fontawesome-free\scss\fontawesome.scss 5:9   @import
    resources\sass\app.scss 1:9                                            root stylesheet

```

**Comment by RoduanKD** [comment]
PS: with the above fix it's working with deprecation notice for font awesome files. @krekas 
image

**Comment by krekas** [comment]
@RoduanKD I checked your pr.

1. adminlte isn't working. Can't open dropdowns. And console shows error
image
2. coreui everything works.
3. plainadmin dropdown also not working
4. volt dropdown again
5. sb admin 2 also dropdowns. Getting jquery error in console 
image
6. tabler everything seems working

**Comment by RoduanKD** [comment]
thanks for your check @krekas:

1. adminlte is fixed
2. plainadmin is fixed 
3. volt is fixed
4. sb admin 2: sidebar toggle is working now and the jQuery error is gone but the dropdown didn't work and I didn't get why is that happening!

**Comment by krekas** [comment]
@RoduanKD 

1. adminlte dropdown works only for menu, where user is doesn't
2. volt gives font error. I think it would be great to fix it
image
3. sb admin 2 is made using bootstrap 4. When downgraded works. I can't push directly to pr here so make these changes.
In `replaceWithSBAdmin2()` function at the start add
```php
// NPM Packages...
$this->updateNodePackages(function ($packages) {
    return [
        "bootstrap" => "^4.6.2",
    ] + $packages;
}, dev: true);
```
In `guest.blade.php` replace css with `@vite('resources/css/app.css')` and in both layouts remove google fonts

**Comment by PovilasKorop** [comment]
@krekas ping, have you had the time to test the latest changes by @RoduanKD?

**Comment by krekas** [comment]
@PovilasKorop planning to check today

**Comment by krekas** [comment]
@RoduanKD change admin LTE npm packages to:
```php
// NPM Packages...
$this->updateNodePackages(function ($packages) {
    return [
            'jquery'=> '^3.6.0',
            'resolve-url-loader' => '^4.0.0',
            'bootstrap' => '~4.6.1',
        ] + $packages;
}, dev: true);
```
this theme also uses old bootstrap version. After this fix everything works.

@PovilasKorop after this last fix green light from me.

**Comment by PovilasKorop** [comment]
@krekas could you maybe do it yourself and push to the branch of PR? Then we wouldn't need to wait for @RoduanKD

**Comment by krekas** [comment]
@PovilasKorop don't have permissions.

**Comment by PovilasKorop** [comment]
@krekas oh right, how could I forget. Ok waiting then.

**Comment by RoduanKD** [comment]
@keras, I've downgraded `bootstrap` in Admin LTE and had to downgrade `jQuery` & `popper.js`, and it's working fine now.

**Comment by PovilasKorop** [comment]
@krekas can you approve that I should merge?

**Comment by krekas** [comment]
@PovilasKorop everything should be good, green light from me

**Pull request merged**
