### PR TITLE
volt bootstrap5 laravel admin theme added

### PR DESCRIPTION
**Pull request by knaazimkhan**

### CODE REVIEW

**Comment by krekas** [comment]
@knaazimkhan thanks for your pr but please fix it if you want it to be merged.

- laravel/breeze uses tailwind not bootstrap. You put everything under breeze not ui
- Please check how replacement is done with other themes using "steps"
- laravel/ui doesn't use components
- Remove charts and other unnecessary things. Haven't checked all files but in one found a lot of commented out code

For now please fix those and check how other themes are done. Then we will review everything again :)

**Comment by knaazimkhan** [comment]
Hi @krekas thanks for your review, as you said, I moved theme from breeze to ui.

- Remove charts and other unnecessary things
- Put everything under ui.
- Follow other themes replacement "steps".
- Profile section added.

Some Screen Shot

1. Login Page
image

2. Registration Page
image

3.  Forgot Password Page
image

4. Reset Password Page
image

5. Dashboard Page
image

**Comment by krekas** [comment]
@knaazimkhan looks good. Can you make some more changes?

- Remove search input
- Remove breadcrumbs
- In register page also add icon to name input
- Navigation doesn't align :thinking:

**Comment by knaazimkhan** [comment]
@krekas all points fix. please take a look...

**Comment by krekas** [comment]
@knaazimkhan installed it and everything looks fine. Just two last fixes before Povilas will check.

- On my profile page we let user to change email and remove profile card on the right
- Can you add one multi-level menu? Just name it "Two-level menu" and "Child menu" and link it just to #

**Comment by knaazimkhan** [comment]
@krekas done.

**Pull request merged**
