### PR TITLE
Add Vite support and improve console output

### PR DESCRIPTION
**Pull request by andrefilsantos**
This PR adds Vite support

### CODE REVIEW

**Comment by krekas** [comment]
@andrefilsantos thanks for pr but did you looked before doing if anyone else did it? And it seems that you haven't checked if everything works. With Laravel/ui it shouldn't

**Comment by andrefilsantos** [comment]
hi, @krekas!
ill test again the themes with laravel/ui

**Comment by krekas** [comment]
@andrefilsantos with ui pr is almost done so maybe don't invest your time in that

**Comment by andrefilsantos** [comment]
OK.  I carefully tested all themes with inertia and livewire.  With laravel/ui I was not so careful 😳

**Comment by PovilasKorop** [comment]
@andrefilsantos thanks for your hard work.
We will probably wait for the https://github.com/LaravelDaily/Larastarters/pull/81 to be fully merged, and then will resolve potential conflicts with yours and will merge yours too.

/cc @krekas

**Comment by andrefilsantos** [comment]
@PovilasKorop awesome. Thanks 👍👍

**Comment by PovilasKorop** [comment]
@andrefilsantos now as I've merged that other PR, there are conflicts with your PR, could you resolve please?

**Comment by andrefilsantos** [comment]
@PovilasKorop done!

**Pull request merged**
