### PR TITLE
added sb-admin-2

### PR DESCRIPTION
**Pull request by pcmehrdad**
added sb-admin-2 , another free, open source, Bootstrap admin theme that was created by Start Bootstrap

[Github Page](https://github.com/StartBootstrap/startbootstrap-sb-admin-2)

### CODE REVIEW

**Comment by krekas** [comment]
@pcmehrdad please make some fixes

- Remove everything with charts
- Bootstrap and jqeury are installed with npm by default. Why aren't they used that way?
- Login/Register pages remove facebook/google login buttons
- Remove search, alert center and messages center
- Use profile dropdown whats the difference between  `Profile` and `Settings`. Just leave profile
- When submitting profile update no success message 
- Again profile page something wrong with validation messages style 
image
- Dashboard page check how others are done. Remove everything from there
- About us page remove card title
- Navigation whats that `Interface`? Remove it I think
- Multi level check how other are named. Everything should be the same
- Remove logout from navigation

**Comment by krekas** [comment]
@pcmehrdad are you planning to make changes?

**Comment by pcmehrdad** [comment]
half of them are done, I do not have much time these days.

**Comment by pcmehrdad** [comment]
@krekas all done .
thanks

**Comment by krekas** [comment]
@pcmehrdad 

- Dashboard still left cards. Please check other templates. When you clean install `laravel/ui` you don't get anything
- Navigation `Dashboard` link always active
- Users table pagination doesn't work?

**Comment by pcmehrdad** [comment]
done!

**Comment by PovilasKorop** [comment]
@pcmehrdad I've merged everything, and with @krekas small fixes, released the new `v1.3` of the package, with your theme. Thanks for the contribution!

**Comment by pcmehrdad** [comment]
Thanks to You Sir @PovilasKorop

**Pull request merged**
